#!/usr/bin/env bash
# Using while loop to display clock from Hour: 0 to Hour: 12

hour=0;

while [ $hour -le 12 ]; do
    echo "Hour: $hour"

    minute=1;
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done

    ((hour++))  
done

