#!/usr/bin/env bash
# Using while loop
#!/bin/bash
hour=0
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  minutes=1  # Reset minutes *before* the inner loop
  while [ $minutes -le 59 ]; do
    echo "$minutes"
    minutes=$((minutes + 1))
  done
  hour=$((hour + 1))
done
