#!/usr/bin/env bash
#using if and else for  check how file is 
if [ -e "school" ]; then
  echo "school file exists"

  if [ -s "school" ]; then
    echo "school file is empty"
  else
    echo "school file is not empty"  # Correct order here
  fi

  if [ -f "school" ]; then
    echo "school is a regular file"
  fi

else
  echo "school file does not exist"
fi
