#!/usr/bin/env bash
#using if and else
if [ school ]; then
echo "school file exists"
 if [ school ]; then
   echo "school file is empty"
   else 
     echo "school file is not empty"
else
"school file does not exist"
fi
