#!/usr/bin/env bash
#Executing the 10-process_and_pid_file script and killing it with ctr+c
PID_FILE="/var/run/myscript.pid"
cleanup() {
    echo "Deleting PID file..."
    rm -f "$PID_FILE"
    exit 0
}
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap cleanup SIGQUIT
echo $$ > "$PID_FILE"
while true
do
    echo "To infinity and beyond"
    sleep 1
done
