#!/usr/bin/env bash
#Executing the 10-process_and_pid_file script and killing it with ctr+c

PID_FILE="/var/run/myscript.pid"

echo $$ > "$PID_FILE"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!";exit' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
